version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "10:00"
  open-pull-requests-limit: 10
  reviewers:
  - ellisio
  assignees:
  - ellisio
  ignore:
  - dependency-name: husky
    versions:
    - 4.3.6
    - 4.3.8
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.0
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
  - dependency-name: handlebars
    versions:
    - 4.7.6
