version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:10.16
    environment:
      NO_UPDATE_NOTIFIER: "1"
    steps:
      - checkout
      - run: sudo npm i npm -g
      - run: npm ci
      - run: npm t
workflows:
  pull-request:
    jobs:
      - test
